name: DimensionRestricter
main: me.Jonnyfant.dimensionrestricter.dimensionrestricter
author: Jonnyfant
version: 2.0
permissions:
  dimensionrestricter.enterend:
    description: Allows users to access the end
  dimensionrestricter.enternether:
    description: Allows users to access the nether